<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GitTfs.Test</RootNamespace>
    <IsTestProject>true</IsTestProject>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ResolveAssemblyReferencesFindRelatedSatellites>false</ResolveAssemblyReferencesFindRelatedSatellites>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GitTfs.VsFake\GitTfs.VsFake.csproj" />
    <ProjectReference Include="..\GitTfs\GitTfs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.30.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="Moq" Version="4.14.7" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.4.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MSTest.TestFramework" Version="4.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>
  <ItemGroup>
    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Integration\GlobalConfigs\mainDefaultBranch.gitconfig" />
    <EmbeddedResource Include="Integration\GlobalConfigs\standard.gitconfig" />
  </ItemGroup>
</Project>
