<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SolutionDir Condition="'$(SolutionDir)' == '' Or '$(SolutionDir)' == '*Undefined*'">$(MSBuildThisFileDirectory)</SolutionDir>

    <LangVersion>14</LangVersion>
    <NoWarn>$(NoWarn);1573;1591;1712;NU1903</NoWarn>
    <!-- <TreatWarningsAsErrors>true</TreatWarningsAsErrors> -->
    <!-- <Nullable>enable</Nullable> -->

    <ImplicitUsings>enable</ImplicitUsings>

    <!-- SourceLink: https://github.com/dotnet/sourcelink -->
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>embedded</DebugType>

    <!-- Opt in to build acceleration in VS (from 17.5 onwards): https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md -->
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>
</Project>
